### ISSUE TITLE
shiftRotate breaks everything

### ISSUE THREAD

**Issue by charlieroberts** [liz-peng/p5.Polar#10]
Hey Liz! the introduction of `shiftRotate` in 7fdf013 seems to break everything? It's being called without a reference to `this` but it's stored in the prototype so `this` is necessary. I guess just putting `this` in front of every call might fix things? I haven't looked all the way through the file and am unsure...

**Comment by liz-peng** [comment]
@charlieroberts Hi Charlie! I made some updates, could you try the new version? [p5.polar.js](https://cdn.jsdelivr.net/gh/liz-peng/p5.Polar@7d843a68beb71e0f3805593630115b6ca6065617/p5.Polar.js) or [p5.polar.min.js](https://cdn.jsdelivr.net/gh/liz-peng/p5.Polar@latest/p5.Polar.min.js). If it's still not working, could you please share your project link/piece of code so I can debug it? I tested the shiftRotate with my repo examples include some animation and they worked fine. Wondering if I missed something so it breaks on your side.

**Comment by charlieroberts** [comment]
Awesome, works great now! Thank you so much!!!
